# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0cfd786978e310ee856b89fbaff550bf0ec1a0d123c27dc15c924452b18d8ec65051994ee57cc75291bbfa306e4f5554e1fd3869d47f95ad71ac07803f4cec78

test:
  secret_key_base: c4c98744b4f285da9fa9be146f344648231c2b0a93c2367c73ca3cb4a419ee5547946ebcead964670a9e39ce374f3eea0903ac6ed97575031e611bf3a931a23c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
